Parameters:
  Vpc:
    Type: 'AWS::EC2::VPC::Id'
  Subnet1:
    Type: 'AWS::EC2::Subnet::Id'
  Subnet2:
    Type: 'AWS::EC2::Subnet::Id'
  ECRRepo:
    Type: 'AWS::ECR::Repository::RepositoryName'

Transform:
  - 'AWS::CodeDeployBlueGreen'
Hooks:
  CodeDeployBlueGreenHook:
    Properties:
      TrafficRoutingConfig:
        Type: TimeBasedCanary
        TimeBasedCanary:
          StepPercentage: 15
          BakeTimeMins: 5
      Applications:
        - Target:
            Type: 'AWS::ECS::Service'
            LogicalID: ECSAddressSpikeService
          ECSAttributes:
            TaskDefinitions:
              - AddressSpikeBlueTaskDefinition
              - AddressSpikeGreenTaskDefinition
            TaskSets:
              - AddressBlueTaskSet
              - AddressGreenTaskSet
            TrafficRouting:
              ProdTrafficRoute:
                Type: 'AWS::ElasticLoadBalancingV2::Listener'
                LogicalID: AddressALBListenerTraffic
              TargetGroups:
                - AddressALBTargetGroupBlue
                - AddressALBTargetGroupGreen
    Type: 'AWS::CodeDeploy::BlueGreen'

Resources:
  AddressSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for LB access
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - CidrIpv6: ::/0
          FromPort: 80
          ToPort: 80
          IpProtocol: TCP
          Description: 'Inbound rule for IPv6 traffic'
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: TCP
          Description: 'Inbound rule for IPv4 traffic'

  AddressSecurityGroupService:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for services access
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !GetAtt AddressSecurityGroup.GroupId
          Description: Inbound rule for all traffic

  AddressALBTargetGroupBlue:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200-399' # Todo Narrow down
      Port: 5010
      Protocol: HTTP
      Tags:
        - Key: Group
          Value: Example
      TargetType: ip
      UnhealthyThresholdCount: 4
      VpcId: !Ref Vpc

  AddressALBTargetGroupGreen:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200-399' # Todo Narrow down
      Port: 5010
      Protocol: HTTP
      Tags:
        - Key: Group
          Value: Example
      TargetType: ip
      UnhealthyThresholdCount: 4
      VpcId: !Ref Vpc

  AddressSpikeALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AddressSecurityGroup
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Tags:
        - Key: Group
          Value: Example
      Type: application
      IpAddressType: ipv4

  AddressALBListenerTraffic:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AddressALBTargetGroupBlue
                Weight: 1
      LoadBalancerArn: !Ref AddressSpikeALB
      Port: 80
      Protocol: HTTP

  AddressALBListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AddressALBTargetGroupBlue
                Weight: 1
      Conditions:
        - Field: http-header
          HttpHeaderConfig:
            HttpHeaderName: User-Agent
            Values:
              - Mozilla
      ListenerArn: !Ref AddressALBListenerTraffic
      Priority: 1

  ECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  AddressSpikeBlueTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ExecutionRoleArn: !GetAtt
        - ECSTaskExecutionRole
        - Arn
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: di-ipv-cri-address-front-dev
          Image: !Ref ECRRepo
          Essential: true
          MemoryReservation: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 5010
              Protocol: tcp
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Family: AddressFESpike

  #### Address cluster creation
  AddressECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties: {}

  ECSAddressSpikeService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref AddressECSCluster
      DesiredCount: 1
      DeploymentController:
        Type: EXTERNAL

  AddressBlueTaskSet:
    Type: 'AWS::ECS::TaskSet'
    Properties:
      Cluster: !Ref AddressECSCluster
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsVpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref AddressSecurityGroupService
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
      PlatformVersion: 1.4.0
      Scale:
        Unit: PERCENT
        Value: 100
      Service: !Ref ECSAddressSpikeService
      TaskDefinition: !Ref AddressSpikeBlueTaskDefinition
      LoadBalancers:
        - ContainerName: di-ipv-cri-address-front-dev
          ContainerPort: 5010
          TargetGroupArn: !Ref AddressALBTargetGroupBlue

  PrimaryTaskSet:
    Type: 'AWS::ECS::PrimaryTaskSet'
    Properties:
      Cluster: !Ref AddressECSCluster
      Service: !Ref ECSAddressSpikeService
      TaskSetId: !GetAtt
        - AddressBlueTaskSet
        - Id
