AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates the necessary components to manage DNS for a Credential Issuer

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  CriName:
    Description: The credential issuer name
    Type: String
    Default: "none"
    AllowedValues:
      - none
      - Passport
  CriSubdomain:
    Description: The unique credential issuer subdomain
    Type: String
    AllowedPattern: "review-.+"
    ConstraintDescription: must match pattern review-.+ i.e. review-a
  FrontStackName:
    Description: The CRI Frontend Stack Name i.e. passport-cri-front
    Type: String
  ApiStackName:
    Description: The CRI Api Stack Name i.e. passport-cri-api
    Type: String

Conditions:
  CreateProdResources: !Equals [ !Ref Environment, production]
  CreateNonProdResources: !Not [!Condition CreateProdResources]

Resources:
  ExternalCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateNonProdResources
    Properties:
      DomainName: !Sub "${CriSubdomain}.${Environment}.account.gov.uk"
      SubjectAlternativeNames:
        - !Sub "api.${CriSubdomain}.${Environment}.account.gov.uk"
      DomainValidationOptions:
        - DomainName: !Sub "${CriSubdomain}.${Environment}.account.gov.uk"
          HostedZoneId: !ImportValue PublicHostedZoneId
        - DomainName: !Sub "api.${CriSubdomain}.${Environment}.account.gov.uk"
          HostedZoneId: !ImportValue PublicHostedZoneId
      ValidationMethod: DNS

  ExternalApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: CreateNonProdResources
    Properties:
      DomainName: !Sub "api.${CriSubdomain}.${Environment}.account.gov.uk"
      DomainNameConfigurations:
        - CertificateArn: !Ref ExternalCertificate
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  ExternalApiRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateNonProdResources
    Properties:
      Name: !Sub "api.${CriSubdomain}.${Environment}.account.gov.uk."
      Type: A
      HostedZoneId: !ImportValue PublicHostedZoneId
      AliasTarget:
        DNSName: !GetAtt ExternalApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ExternalApiCustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  ExternalApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: CreateNonProdResources
    Properties:
      DomainName: !Sub "api.${CriSubdomain}.${Environment}.account.gov.uk"
      ApiId:
        Fn::ImportValue:
          !Sub ${ApiStackName}-${CriName}ApiGatewayId
      Stage: !Ref Environment
    DependsOn:
      - ExternalApiCustomDomain

  FrontCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: CreateNonProdResources
    Properties:
      DomainName: !Sub "${CriSubdomain}.${Environment}.account.gov.uk"
      DomainNameConfigurations:
        - CertificateArn: !Ref ExternalCertificate
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  FrontApiRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateNonProdResources
    Properties:
      Name: !Sub "${CriSubdomain}.${Environment}.account.gov.uk."
      Type: A
      HostedZoneId: !ImportValue PublicHostedZoneId
      AliasTarget:
        DNSName: !GetAtt FrontCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt FrontCustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  FrontApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: CreateNonProdResources
    Properties:
      DomainName: !Sub "${CriSubdomain}.${Environment}.account.gov.uk"
      ApiId:
        Fn::ImportValue:
          !Sub ${FrontStackName}-${CriName}FrontGatewayId
      Stage: "$default"
    DependsOn:
      - FrontCustomDomain

  ProdExternalCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateProdResources
    Properties:
      DomainName: !Sub "${CriSubdomain}.account.gov.uk"
      SubjectAlternativeNames:
        - !Sub "api.${CriSubdomain}.account.gov.uk"
      DomainValidationOptions:
        - DomainName: !Sub "${CriSubdomain}.account.gov.uk"
          HostedZoneId: !ImportValue PublicHostedZoneId
        - DomainName: !Sub "api.${CriSubdomain}.account.gov.uk"
          HostedZoneId: !ImportValue PublicHostedZoneId
      ValidationMethod: DNS

  ProdExternalApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: CreateProdResources
    Properties:
      DomainName: !Sub "api.${CriSubdomain}.account.gov.uk"
      DomainNameConfigurations:
        - CertificateArn: !Ref ProdExternalCertificate
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  ProdExternalApiRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateProdResources
    Properties:
      Name: !Sub "api.${CriSubdomain}.account.gov.uk."
      Type: A
      HostedZoneId: !ImportValue PublicHostedZoneId
      AliasTarget:
        DNSName: !GetAtt ProdExternalApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ProdExternalApiCustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  ProdExternalApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: CreateProdResources
    Properties:
      DomainName: !Sub "api.${CriSubdomain}.account.gov.uk"
      ApiId:
        Fn::ImportValue:
          !Sub ${ApiStackName}-${CriName}ApiGatewayId
      Stage: !Ref Environment
    DependsOn:
      - ProdExternalApiCustomDomain

  ProdFrontCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: CreateProdResources
    Properties:
      DomainName: !Sub "${CriSubdomain}.account.gov.uk"
      DomainNameConfigurations:
        - CertificateArn: !Ref ProdExternalCertificate
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  ProdFrontApiRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateProdResources
    Properties:
      Name: !Sub "${CriSubdomain}.account.gov.uk."
      Type: A
      HostedZoneId: !ImportValue PublicHostedZoneId
      AliasTarget:
        DNSName: !GetAtt ProdFrontCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ProdFrontCustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  ProdFrontApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: CreateProdResources
    Properties:
      DomainName: !Sub "${CriSubdomain}.account.gov.uk"
      ApiId:
        Fn::ImportValue:
          !Sub ${FrontStackName}-${CriName}FrontGatewayId
      Stage: "$default"
    DependsOn:
      - ProdFrontCustomDomain
