name: Package core infrastructure
on:
  push:
    branches:
      - main
    paths:
      - "core/**"
  workflow_dispatch: # deploy manually

jobs:
  publish_core_to_matrix_dev:
    strategy:
      matrix:
        target: [ ADDRESS_DEV, FRAUD_DEV, KBV_DEV, KBV_POC, DL_DEV ]
        include:
          - target: ADDRESS_DEV
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: ADDRESS_DEV_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET: ADDRESS_DEV_CORE_GH_ACTIONS_ROLE_ARN
          - target: FRAUD_DEV
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: FRAUD_DEV_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET: FRAUD_DEV_CORE_GH_ACTIONS_ROLE_ARN
          - target: KBV_DEV
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: KBV_DEV_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET: KBV_DEV_CORE_GH_ACTIONS_ROLE_ARN
          - target: KBV_POC
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: KBV_POC_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET: KBV_POC_CORE_GH_ACTIONS_ROLE_ARN
          - target: DL_DEV
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: DL_DEV_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET: DL_DEV_CORE_GH_ACTIONS_ROLE_ARN
      max-parallel: 2
    name: Publish core infrastructure to dev
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t core/template.yaml

      - name: SAM build
        run: sam build -t core/template.yaml

      - name: SAM package
        run: |
          sam package -t core/template.yaml  \
            --s3-bucket ${{ secrets[matrix.ARTIFACT_SOURCE_BUCKET_NAME_SECRET] }} \
            --region ${{ env.AWS_REGION }} --output-template-file=cf-template.yaml

      - name: Zip the CloudFormation template
        run: zip template.zip cf-template.yaml

      - name: Upload zipped CloudFormation artifact to S3
        env:
          ARTIFACT_SOURCE_BUCKET_NAME: ${{ secrets[matrix.ARTIFACT_SOURCE_BUCKET_NAME_SECRET] }}
        run: aws s3 cp template.zip "s3://${{ env.ARTIFACT_SOURCE_BUCKET_NAME }}/template.zip"


  publish_core_to_matrix_build:
    needs: publish_core_to_matrix_dev
    strategy:
      matrix:
        target: [ ADDRESS_BUILD, FRAUD_BUILD, KBV_BUILD, DL_BUILD ]
        include:
          - target: ADDRESS_BUILD
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: ADDRESS_BUILD_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET:    ADDRESS_BUILD_CORE_GH_ACTIONS_ROLE_ARN
          - target: FRAUD_BUILD
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: FRAUD_BUILD_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET:    FRAUD_BUILD_CORE_GH_ACTIONS_ROLE_ARN
          - target: KBV_BUILD
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: KBV_BUILD_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET:    KBV_BUILD_CORE_GH_ACTIONS_ROLE_ARN
           - target: DL_BUILD
            ARTIFACT_SOURCE_BUCKET_NAME_SECRET: DL_BUILD_CORE_ARTIFACT_SOURCE_BUCKET_NAME
            GH_ACTIONS_ROLE_ARN_SECRET: DL_BUILD_CORE_GH_ACTIONS_ROLE_ARN
      max-parallel: 2
    name: Publish core infrastructure to build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t core/template.yaml

      - name: SAM build
        run: sam build -t core/template.yaml

      - name: SAM package
        run: |
          sam package -t core/template.yaml  \
            --s3-bucket ${{ secrets[matrix.ARTIFACT_SOURCE_BUCKET_NAME_SECRET] }} \
            --region ${{ env.AWS_REGION }} --output-template-file=cf-template.yaml

      - name: Zip the CloudFormation template
        run: zip template.zip cf-template.yaml

      - name: Upload zipped CloudFormation artifact to S3
        env:
          ARTIFACT_SOURCE_BUCKET_NAME: ${{ secrets[matrix.ARTIFACT_SOURCE_BUCKET_NAME_SECRET] }}
        run: aws s3 cp template.zip "s3://${{ env.ARTIFACT_SOURCE_BUCKET_NAME }}/template.zip"
